import localFont from 'next/font/local';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { ThemeProvider } from '@/context/ThemeContext';
import './globals.css';

const primaryFont = localFont({
  src: [
    {
      path: './fonts/SportingGrotesque-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/SportingGrotesque-Bold.otf',
      weight: '700',
      style: 'normal',
    },
  ],
});

const secondaryFont = localFont({
  src: [
    {
      path: './fonts/BwGradualDEMO-ExtraBold.otf',
      weight: '800',
      style: 'normal',
    },
  ],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${primaryFont.className} ${secondaryFont.className}`}
    >
      <body className="min-h-screen flex flex-col transition-colors duration-300 ease-out">
        <ThemeProvider>
          <Header />
          <main>{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
